version: '3.9'

services:
    elkSearch:
        container_name: elasticsearch
        image: elasticsearch:7.14.2
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - cluster.name=elasticsearch_01
            - discovery.type=single-node
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
            - logger.level=ERROR
        volumes:
          - elkdb:/usr/share/elasticsearch/data
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536
    elkKibana:
      image: kibana:7.14.2
      ports:
          - 5601:5601
      depends_on:
        - "elasticsearch"
volumes:
  elkdb:
